import { useState } from "react";
import { ArrowLeft, ArrowRight, Download, Eye, Trash2 } from "lucide-react";
import type { BackendReport } from "../../api/types";
import { downloadInspectionPdf } from "../../api/client";
import { groupInspections, maximumSeverity, reportPhotos, severityLabels, formatReportDate } from "../../utils/reportInsights";
import { EvidenceGallery } from "./EvidenceGallery";
export function InspectionOverview({reports,onBack,onReport,onDelete}: {reports:BackendReport[];onBack:()=>void;onReport:(code:string)=>void;onDelete?:(report:BackendReport)=>void}) {
  const [error,setError]=useState(""),[downloading,setDownloading]=useState(false);
  const group=groupInspections(reports)[0];
  if(!group)return null;
  const accepted=reports.filter(r=>r.status!=="REJECTED");
  const severity=maximumSeverity(accepted);
  const byAsset=new Map<number,BackendReport[]>();
  group.reports.forEach(r=>{if(r.idAsset!==null)byAsset.set(r.idAsset,[...(byAsset.get(r.idAsset)??[]),r]);});
  const exportPdf=async(inline:boolean)=>{setError("");setDownloading(true);try{await downloadInspectionPdf(group.id,[...byAsset.keys()],inline);}catch(e){setError(e instanceof Error ? e.message : "No se pudo exportar la inspección");}finally{setDownloading(false);}};
  return <section className="inspection-overview"><button className="report-link" onClick={onBack}><ArrowLeft size={15}/> Volver al historial</button><header className="report-card report-section-heading"><div><span className="reports-eyebrow">REPORTE POR INSPECCIÓN</span><h2>{group.name}</h2><p>{formatReportDate(group.date)} · {byAsset.size} activos con evidencia</p></div><div className="report-actions-row"><button disabled={downloading} className="report-secondary" onClick={()=>void exportPdf(true)}><Eye size={16}/> Visualizar PDF</button><button disabled={downloading} className="reports-ai-button" onClick={()=>void exportPdf(false)}><Download size={16}/> Descargar inspección</button></div></header>{error&&<p role="alert" className="reports-feedback error">{error}</p>}<section className="report-card inspection-executive-summary"><span className="reports-eyebrow">RESUMEN DE LA INSPECCIÓN</span><h2>{accepted.some(r=>r.findingsCount>0) ? `Mayor gravedad informada: ${severityLabels[severity].toLowerCase()}` : "Resultados de la inspección"}</h2><p>{reportPhotos(reports).length} capturas · {accepted.reduce((s,r)=>s+(r.corrosionFindingsCount??0),0)||0} con corrosión · {accepted.reduce((s,r)=>s+(r.crackFindingsCount??0),0)} con fisuras / grietas</p><p>Los activos se presentan de mayor a menor gravedad. Los resultados pendientes o descartados mantienen su estado; las grietas sin gravedad estimada requieren revisión.</p></section>{[...byAsset.entries()].map(([id,items])=><section className="report-card inspection-asset-group" key={id}><header className="report-section-heading"><div><h2>{items[0].assetName}</h2><p>{reportPhotos(items).length} capturas · Gravedad: {severityLabels[maximumSeverity(items.filter(r=>r.status!=="REJECTED"))]}</p></div></header><div className="inspection-asset-reports">{items.map(r=><div key={r.code}><span className="report-badge gray">{r.status==="VALIDATED" ? "Validado" : r.status==="REJECTED" ? "Descartado" : r.status==="PROCESSING" ? "Procesando" : "Pendiente de validación"}</span><button className="report-link" onClick={()=>onReport(r.code)}>Abrir reporte y validación · {r.code}<ArrowRight size={14}/></button>{onDelete && <button className="report-icon-button" aria-label={`Eliminar registro de ${r.assetName}`} onClick={()=>onDelete(r)}><Trash2 size={15}/></button>}</div>)}</div><EvidenceGallery photos={reportPhotos(items)} onReport={onReport}/></section>)}</section>;
}
